# Build and test code for Android and Windows.
# Workfile written using ChatGPT.
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    # Install .NET MAUI for Android ...
    # Install macOS tools ...
    # Perform dotnet restore ...
    - name: Install dependencies
      run: |
        dotnet workload install maui-android
        dotnet workload install maccatalyst
        dotnet restore
    - name: Build and test for Android
      run: dotnet build --configuration Release --framework net7.0-android && dotnet test --no-build --configuration Release --framework net7.0-android

    - name: Build and test for Windows
      run: dotnet build --configuration Release --framework net6.0-windows && dotnet test --no-build --configuration Release --framework net6.0-windows
