# Define when the workflow is run
name: CI Build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:

  # Build the application for an Android environment.
  build-android:
    runs-on: windows-latest
    name: Android Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore Dependencies
      run: dotnet restore TournamentOrganizer/TournamentOrganizer.csproj /p:PublishReadyToRun=true
      
    - name: Build Project
      run: dotnet build TournamentOrganizer/TournamentOrganizer.csproj -c Release -f net7.0-android33.0 --no-restore
      
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: TournamentOrganizer-android-ci-build
        path: TournamentOrganizer/bin/Release/net7.0-android33.0/*Signed.a*      

  # Build the application for a Windows environment.
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TournamentOrganizer/TournamentOrganizer.csproj /p:PublishReadyToRun=true

      - name: Build MAUI Windows
        run: dotnet publish TournamentOrganizer/TournamentOrganizer.csproj -c Release -f net7.0-windows10.0.22621.0 --no-restore /p:AndroidSigningKeyPass=$KEY_PASSWORD /p:AndroidSigningStorePass=$KEYSTORE_PASSWORD

      - name: Sign APK with secret
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROIDSIGNINGSTOREPASS }}
          KEY_PASSWORD: ${{ secrets.ANDROIDSIGNINGKEYPASS }}
        run: |
          echo $KEYSTORE | base64 --decode > keystore.jks
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass $ANDROIDSIGNINGSTOREPASS -keypass $ANDROIDSIGNINGKEYPASS app/build/outputs/apk/release/app-release-unsigned.apk alias_name
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TournamentOrganizer-windows-ci-build
          path: TournamentOrganizer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/TournamentOrganizer*.exe

