name: CI Build

# Define when the workflow is run
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:

  # Build the application for an Android environment.
  build-android:

    runs-on: windows-latest
    name: Android Build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install MAUI workload
      run: |
        dotnet workload install maui-android
        dotnet workload install maui-maccatalyst
        dotnet workload install ios
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # Build the application for a Windows environment.
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build MAUI Windows
        run: dotnet build --no-restore

  # Build the application for an iOS environment.
  build-ios:
    runs-on: macos-latest
    name: iOS Build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios
          dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build MAUI iOS
        run: dotnet build --no-restore
